### ISSUE TITLE
Not an issue but a suggestion

### ISSUE THREAD

**Issue by robinsg** [IBM/SVCheck#1]
I have downloaded SVCheck and created a requirements.txt file containing:

requests
openpyxl
pandas

Then run:
pip3 install -r requirements.txt

I know you'll be more than aware of this but it just makes the installation simpler so may be worth adding to the repository and amending the README.

**Comment by bolinches** [comment]
Hi

Different people prefer different ways to setup their ways to setup their runtime. But I think is a fair point. Instead of creating the file and readme I think I will link to a wiki page suggesting 2 or 3 ways to setup the prerequisites

Thanks

**Comment by robinsg** [comment]
Yeah, sounds good.

Thanks

**Comment by bolinches** [comment]
https://github.com/IBM/SVCheck/wiki/How-to-install-the-prerequisites

**Comment by bolinches** [comment]
"Fixed" on https://github.com/IBM/SVCheck/commit/7986282725513a33dd405f7d888a15828ee02f9a
